"""empty message

Revision ID: 54bbdd7d5c01
Revises: 2747f567b552
Create Date: 2021-02-14 09:50:35.876087+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54bbdd7d5c01'
down_revision = '2747f567b552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('version', sa.INTEGER(), nullable=False, comment='バージョン（楽観排他制御用）'))
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=False, comment='パスワード'))
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), nullable=True, comment='ユーザー名'))
    op.add_column('users', sa.Column('version', sa.INTEGER(), nullable=False, comment='バージョン（楽観排他制御用）'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=254),
               comment='メールアドレス',
               existing_nullable=False)
    op.drop_column('users', 'title')
    op.drop_column('users', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='記事本文'))
    op.add_column('users', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False, comment='タイトル'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=254),
               comment=None,
               existing_comment='メールアドレス',
               existing_nullable=False)
    op.drop_column('users', 'version')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    op.drop_column('articles', 'version')
    # ### end Alembic commands ###
