"""empty message

Revision ID: 21ca8e8d227b
Revises: 27f9237df0b0
Create Date: 2021-02-14 06:06:52.714410+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21ca8e8d227b'
down_revision = '27f9237df0b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_tags',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.Column('name', sa.TEXT(), nullable=False, comment='記事に付与するタグの名称'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('articles', 'uuid',
               existing_type=sa.TEXT(),
               comment='画面表示用のID',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'uuid',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='画面表示用のID',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_table('m_tags')
    # ### end Alembic commands ###
