"""empty message

Revision ID: 27f9237df0b0
Revises: 3616411b846f
Create Date: 2021-02-14 06:00:53.036815+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f9237df0b0'
down_revision = '3616411b846f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('uuid', sa.TEXT(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_index(op.f('ix_articles_uuid'), 'articles', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_articles_uuid'), table_name='articles')
    op.drop_column('articles', 'uuid')
    # ### end Alembic commands ###
