"""empty message

Revision ID: 24ba811cfe3c
Revises: 9ce6efe1c023
Create Date: 2021-02-14 09:37:49.156988+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24ba811cfe3c'
down_revision = '9ce6efe1c023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='登録日時'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='最終更新日時'),
    sa.Column('uuid', sa.TEXT(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='画面表示用のID'),
    sa.Column('email', sa.VARCHAR(length=254), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False, comment='タイトル'),
    sa.Column('content', sa.TEXT(), nullable=False, comment='記事本文'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
