"""empty message

Revision ID: bd5f20a15fe8
Revises: cb4c22964989
Create Date: 2021-02-14 09:44:04.739663+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5f20a15fe8'
down_revision = 'cb4c22964989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('active_unique_email_idx', 'users', ['email'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('content_idx', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('content_idx', 'users', ['content'], unique=False)
    op.drop_index('active_unique_email_idx', table_name='users')
    # ### end Alembic commands ###
