"""empty message

Revision ID: 3b76be62b0bd
Revises: 24ba811cfe3c
Create Date: 2021-02-14 09:41:26.503246+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b76be62b0bd'
down_revision = '24ba811cfe3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
