"""empty message

Revision ID: 9ce6efe1c023
Revises: 46914afcea26
Create Date: 2021-02-14 06:12:53.435957+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce6efe1c023'
down_revision = '46914afcea26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_m_tags', sa.Column('article_id', sa.INTEGER(), nullable=True))
    op.add_column('article_m_tags', sa.Column('m_tag_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'article_m_tags', 'm_tags', ['m_tag_id'], ['id'])
    op.create_foreign_key(None, 'article_m_tags', 'articles', ['article_id'], ['id'])
    op.drop_column('article_m_tags', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_m_tags', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False, comment='記事に付与するタグの名称'))
    op.drop_constraint(None, 'article_m_tags', type_='foreignkey')
    op.drop_constraint(None, 'article_m_tags', type_='foreignkey')
    op.drop_column('article_m_tags', 'm_tag_id')
    op.drop_column('article_m_tags', 'article_id')
    # ### end Alembic commands ###
