"""empty message

Revision ID: cb4c22964989
Revises: 3b76be62b0bd
Create Date: 2021-02-14 09:43:33.294123+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4c22964989'
down_revision = '3b76be62b0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('content_idx', 'users', ['content'], unique=False)
    op.drop_index('ix_users_uuid', table_name='users')
    op.create_unique_constraint(None, 'users', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_uuid', 'users', ['uuid'], unique=True)
    op.drop_index('content_idx', table_name='users')
    # ### end Alembic commands ###
