"""empty message

Revision ID: 2747f567b552
Revises: bd5f20a15fe8
Create Date: 2021-02-14 09:45:45.681852+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2747f567b552'
down_revision = 'bd5f20a15fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('active_unique_email_idx', table_name='users')
    op.create_index('active_unique_email_idx', 'users', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index('active_unique_email_idx', table_name='users')
    op.create_index('active_unique_email_idx', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
