"""empty message

Revision ID: 52b643253c1f
Revises: 54bbdd7d5c01
Create Date: 2021-02-14 09:51:33.444134+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b643253c1f'
down_revision = '54bbdd7d5c01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
